//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajero
    {
        public int ID { get; set; }
        public Nullable<int> Edad_0_5 { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<int> IdRegistroViaje { get; set; }
        public Nullable<int> Edad_6_18 { get; set; }
        public Nullable<int> Edad_19_65 { get; set; }
    
        public virtual RegistroViaje RegistroViaje { get; set; }
    }
}
