//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroViajes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RegistroViaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistroViaje()
        {
            this.Pasajeros = new HashSet<Pasajero>();
        }

        public int ID { get; set; }
        public string PaisOrigen { get; set; }
        public string PaisDestino { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; } = DateTime.Now;

        public virtual pai pai { get; set; }
        public virtual pai pai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasajero> Pasajeros { get; set; }
        [NotMapped]
        public int Cantidad_OP1 { get; set; }
        [NotMapped]
        public int Cantidad_OP2 { get; set; }
        [NotMapped]
        public int Cantidad_OP3 { get; set; }

    }
}
